// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes the sentiment of user feedback and categorizes it by topic.
 *
 * - analyzeFeedbackSentiment - A function that analyzes feedback for sentiment and topic.
 * - AnalyzeFeedbackSentimentInput - The input type for the analyzeFeedbackSentiment function.
 * - AnalyzeFeedbackSentimentOutput - The return type for the analyzeFeedbackSentiment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeFeedbackSentimentInputSchema = z.object({
  feedbackText: z
    .string()
    .describe('The text of the user feedback to be analyzed.'),
});
export type AnalyzeFeedbackSentimentInput = z.infer<
  typeof AnalyzeFeedbackSentimentInputSchema
>;

const AnalyzeFeedbackSentimentOutputSchema = z.object({
  sentiment: z
    .string()
    .describe(
      'The sentiment of the feedback, such as positive, negative, or neutral.'
    ),
  topic: z
    .string()
    .describe('The main topic of the feedback, such as UI, features, or support.'),
  confidence: z
    .number()
    .describe('The confidence level of the sentiment analysis and topic categorization'),
});
export type AnalyzeFeedbackSentimentOutput = z.infer<
  typeof AnalyzeFeedbackSentimentOutputSchema
>;

export async function analyzeFeedbackSentiment(
  input: AnalyzeFeedbackSentimentInput
): Promise<AnalyzeFeedbackSentimentOutput> {
  return analyzeFeedbackSentimentFlow(input);
}

const analyzeFeedbackSentimentPrompt = ai.definePrompt({
  name: 'analyzeFeedbackSentimentPrompt',
  input: {schema: AnalyzeFeedbackSentimentInputSchema},
  output: {schema: AnalyzeFeedbackSentimentOutputSchema},
  prompt: `You are an AI assistant specializing in analyzing customer feedback.

  Analyze the following feedback text for sentiment and categorize it by topic. Also, provide a confidence score for your analysis.

  Feedback Text: {{{feedbackText}}}

  Respond in a JSON format with the following keys: sentiment, topic, confidence.
  The sentiment should be one of: positive, negative, or neutral.
  The topic should be one of: UI, features, support, or other.
  The confidence should be a number between 0 and 1.
  `,
});

const analyzeFeedbackSentimentFlow = ai.defineFlow(
  {
    name: 'analyzeFeedbackSentimentFlow',
    inputSchema: AnalyzeFeedbackSentimentInputSchema,
    outputSchema: AnalyzeFeedbackSentimentOutputSchema,
  },
  async input => {
    const {output} = await analyzeFeedbackSentimentPrompt(input);
    return output!;
  }
);
